export const GET_FLAG_RESULT = "GET_FLAG_RESULT";
export const WAIT_FOR_FLAG_RESULT = "WAIT_FOR_FLAG_RESULT";
export const HANDLE_FLAG_RESULT = "HANDLE_FLAG_RESULT";
export const HANDLE_FLAG_ERROR = "HANDLE_FLAG_ERROR";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_WAIT_FOR_RESULT = "AUTH_WAIT_FOR_RESULT";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_SWITCH_TYPE = "AUTH_SWITCH_TYPE";
export const AUTH_UPDATE_USER_INFO = "AUTH_UPDATE_USER_INFO";

export const QUIZ_GOTO_START_SCREEN = "QUIZ_GOTO_START_SCREEN";
export const QUIZ_FETCH = "QUIZ_FETCH";
export const QUIZ_FETCH_FAIL = "QUIZ_FETCH_FAIL";
export const QUIZ_ANSWER_CHOSEN = "QUIZ_ANSWER_CHOSEN";
export const QUIZ_MOVE_TO_NEXT_QUESTION = "QUIZ_MOVE_TO_NEXT_QUESTION";
export const QUIZ_START_GAME = "QUIZ_START_GAME";
export const QUIZ_QUESTION_BEGIN = "QUIZ_QUESTION_BEGIN";
export const QUIZ_UPDATE_PROGRESS_BAR = "QUIZ_UPDATE_PROGRESS_BAR";
export const QUIZ_WAIT_FOR_ASYNC_RESULT = "QUIZ_WAIT_FOR_ASYNC_RESULT";
export const QUIZ_SUBMIT_SCORE_SUCCESS = "QUIZ_SUBMIT_SCORE_SUCCESS";
export const QUIZ_SUBMIT_SCORE_FAIL = "QUIZ_SUBMIT_SCORE_FAIL";
export const QUIZ_CLOSE_CONGRATULATION_MODAL = "QUIZ_CLOSE_CONGRATULATION_MODAL";
export const QUIZ_FETCH_SCORE_RECORDS_SUCESS = "QUIZ_FETCH_SCORE_RECORD_SUCESS"; 
export const QUIZ_FETCH_SCORE_RECORDS_FAIL = "QUIZ_FETCH_SCORE_RECORD_FAIL";
export const QUIZ_WAIT_FOR_SCORE_RECORDS_RESULT = "QUIZ_WAIT_FOR_SCORE_RECORDS_RESULT";